server:
  servlet:
    context-path: /ibook

spring:  #生产环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ibook?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#
projecturl:
  ibook: http://127.0.0.1:8080/ibook
  bookImageSavePath: D:/Gitrepository/ibook/src/main/resources/static/photo/books/